### ISSUE TITLE
Available Moves

### ISSUE THREAD

**Issue by ja4200wi** [ja4200wi/backgammon#4]
I would like to see which spikes I could move to given the current dice roll and source spike I selected. Also the communication of illegal moves and pressing of spikes should work smoother.

AC:

- [x] Visually highlight spikes that could be visited
- [x] Communicate deactive checkers that can't be moved in this turn?
- [ ] Show what moves are still left: when a player has 5,3 and has already moved 5 steps with a checker this should be clear

**Comment by moritzKallax** [comment]
- grey out used dice

**Comment by ja4200wi** [comment]
We cover the grey out of dice in #8
